/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalprogramacion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Santi Cereda
 */
public class MenuCuenta extends javax.swing.JFrame {

    /**
     * Creates new form MenuCuenta
     */
    private int id;
    BaseDeDatos operaciones;

    public MenuCuenta(int id, BaseDeDatos operaciones) {
        this.operaciones = operaciones;
        this.id = id;
        initComponents();

        btnConsulta.addActionListener(new consultarMonto(id, operaciones));
        btnIngresar.addActionListener(new ingresarMonto(id, operaciones));
        btnRetiro.addActionListener(new retirarMonto(id, operaciones));
        btnTransferencia.addActionListener(new transferenciaDinero(id, operaciones));
        btnMostrarDatos.addActionListener(new imprimirDatos(id, operaciones));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConsulta = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnTransferencia = new javax.swing.JButton();
        btnRetiro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCambios = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDatosCliente = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnMostrarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        btnConsulta.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnConsulta.setText("Consultar Monto");

        btnIngresar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnIngresar.setText("Ingresar Monto");

        btnTransferencia.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnTransferencia.setText("Transferencia");

        btnRetiro.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnRetiro.setText("Retirar Monto");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("<<<");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("<<<");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText(">>>");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText(">>>");

        txtCambios.setColumns(20);
        txtCambios.setRows(5);
        jScrollPane1.setViewportView(txtCambios);

        txtDatosCliente.setEditable(false);
        txtDatosCliente.setColumns(20);
        txtDatosCliente.setRows(5);
        jScrollPane2.setViewportView(txtDatosCliente);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setText("Ingrese el valor deseado:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setText("Estado actual:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setText(">>>");

        btnMostrarDatos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnMostrarDatos.setText("Mostrar Datos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnIngresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMostrarDatos))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRetiro))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnConsulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTransferencia)))
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsulta)
                    .addComponent(btnTransferencia)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 82, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btnMostrarDatos))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRetiro)
                            .addComponent(jLabel5)
                            .addComponent(btnIngresar)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private class consultarMonto implements ActionListener {

        private int id;
        private BaseDeDatos operaciones;

        public consultarMonto(int id, BaseDeDatos operaciones) {
            this.id = id;
            this.operaciones = operaciones;
        }

        @Override
        public void actionPerformed(ActionEvent e) {

            double monto = operaciones.consultarMonto(id);

            txtDatosCliente.setText("$" + String.valueOf(monto));

        }

    }

    private class ingresarMonto implements ActionListener {

        private int id;
        private double monto;
        private BaseDeDatos operaciones;

        public ingresarMonto(int id, BaseDeDatos operaciones) {
            this.id = id;
            this.operaciones = operaciones;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            monto = Double.parseDouble(txtCambios.getText());

            double resultado = operaciones.ingresarDinero(id, monto);

            txtDatosCliente.setText("$" + String.valueOf(resultado));

            txtCambios.setText("");
            txtDatosCliente.setText("");

            JFrame frame = new JFrame("Validacion Ingreso");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(300, 150);

            JOptionPane.showMessageDialog(frame, "Ingreso Exitoso");
        }

    }

    private class retirarMonto implements ActionListener {

        private int id;
        private double monto;
        private BaseDeDatos operaciones;

        public retirarMonto(int id, BaseDeDatos operaciones) {
            this.id = id;
            this.operaciones = operaciones;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            monto = Double.parseDouble(txtCambios.getText());

            double resultado = operaciones.retirarDinero(id, monto);

            txtDatosCliente.setText("$" + String.valueOf(resultado));
            txtCambios.setText("");
            txtDatosCliente.setText("");

        }

    }

    private class transferenciaDinero implements ActionListener {

        private int id;
        private BaseDeDatos operaciones;

        public transferenciaDinero(int id, BaseDeDatos operaciones) {
            this.operaciones = operaciones;
            this.id = id;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            Transferencia transferencia = new Transferencia(id, operaciones);
            transferencia.setVisible(true);

            txtDatosCliente.setText("");
        }

    }

    private class imprimirDatos implements ActionListener {

        private int id;
        private BaseDeDatos operaciones;

        public imprimirDatos(int id, BaseDeDatos operaciones) {
            this.id = id;
            this.operaciones = operaciones;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            DatosCliente datos = new DatosCliente(id, operaciones);
            datos.setVisible(true);

            txtDatosCliente.setText("");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnMostrarDatos;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCambios;
    private javax.swing.JTextArea txtDatosCliente;
    // End of variables declaration//GEN-END:variables
}
